# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-31 14:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Being',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('birth', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
